### ISSUE TITLE
Error on importing or creating account

### ISSUE THREAD

**Issue by dariocast** [RootSoft/algorand-dart#4]
```
E/flutter (31545): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Unhandled error type 'Null' is not a subtype of type 'int' in type cast occurred in Instance of 'WalletBloc'.
E/flutter (31545): #0      List.length= (dart:core-patch/growable_array.dart:222:12)
E/flutter (31545): #1      _IntListMixin.+ (dart:typed_data-patch/typed_data_patch.dart:156:9)
E/flutter (31545): #2      Address.encodeAddress
package:algorand_dart/…/addresses/address_model.dart:53
E/flutter (31545): #3      new Address
package:algorand_dart/…/addresses/address_model.dart:24
E/flutter (31545): #4      new Account._create
package:algorand_dart/…/accounts/account_model.dart:17
E/flutter (31545): #5      Account.fromSeed
package:algorand_dart/…/accounts/account_model.dart:48
E/flutter (31545): <asynchronous suspension>
E/flutter (31545): #6      Algorand.restoreAccount
package:algorand_dart/src/algorand.dart:106
E/flutter (31545): <asynchronous suspension>
E/flutter (31545): #7      AccountRepository.importAccount
package:flutter_algorand_wallet/repositories/account_repository.dart:54
E/flutter (31545): <asynchronous suspension>
E/flutter (31545): #8      WalletBloc.mapEventToState
package:flutter_algorand_wallet/…/bloc/wallet_bloc.dart:33
E/flutter (31545): <asynchronous suspension>
```

**Comment by RootSoft** [comment]
What version of dart are you using @dariocast ?
Can you update your dart & flutter SDK to the latest version and try again?

There used to be a bug in the +-operator in null-safety: https://github.com/dart-lang/sdk/issues/45140

**Comment by dariocast** [comment]
> What version of dart are you using @dariocast ?
> Can you update your dart & flutter SDK to the latest version and try again?
> 
> There used to be a bug in the +-operator in null-safety: [dart-lang/sdk#45140](https://github.com/dart-lang/sdk/issues/45140)

Thanks, updating flutter and dart worked!
